name: Build Application

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  ARTIFACT_RETENTION_DAYS: 7  # 设置构件保留天数:cite[2]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']
        include:
          - os: ubuntu-latest
            artifact-name: linux-package
          - os: macos-latest
            artifact-name: macos-package
          - os: windows-latest
            artifact-name: windows-package

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 也更新 checkout 动作版本

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 安装uv
      run: |
        pip install uv

    - name: 安装依赖
      run: |
        uv sync --all-groups --frozen

    - name: 打包
      run: |
        uv run pyinstaller --onefile main.py

    - name: 上传文件
      uses: actions/upload-artifact@v4  # 更新为 v4 版本
      with:
        name: ${{ matrix.artifact-name }}-${{ github.sha }}
        path: |
          dist/
          build/
        retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
        if-no-files-found: error  # 可选：当没有找到文件时的行为，可选 warn, error, ignore:cite[2]
