name: Build Application

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

env:
  ARTIFACT_RETENTION_DAYS: 7  # 设置构件保留天数:cite[2]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']
        include:
          - os: ubuntu-latest
            artifact-name: linux-package
          - os: macos-latest
            artifact-name: macos-package
          - os: windows-latest
            artifact-name: windows-package

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 也更新 checkout 动作版本

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 安装uv
      run: |
        pip install uv

    - name: 安装依赖
      run: |
        uv sync --all-groups --frozen

    - name: 打包
      run: |
        uv run pyinstaller --onefile --noconsole main.py

    - name: 压缩文件
      run: |
        cd dist && tar -czvf ../${{ matrix.os }}.tar.gz ./* && cd -
        ls 
    
    - name: 上传文件
      # 仅当推送以 'v' 开头的标签时执行（例如 v1.0.0）
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: ${{ matrix.os }}.tar.gz
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
